security:
  oauth2:
    client:
      clientId: 
      clientSecret: 
      accessTokenUri: 
      userAuthorizationUri: 
    resource:
      userInfoUri: 

spring:
  main:
    allow-bean-definition-overriding: true